## Github URL: https://github.com/LaraDock/docker-images/tree/master/data
## Docker URL: https://hub.docker.com/r/laradock/data
#########################################################################
FROM phusion/baseimage:0.9.17

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

CMD ["true"]
